export const CONFIG_VAR = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',

  // DATABASE
  DATABASE_URL: 'DATABASE_URL',

  // JWT
  JWT_SECRET: 'JWT_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  ADMIN_JWT_SECRET: 'ADMIN_JWT_SECRET',
  ADMIN_JWT_REFRESH_SECRET: 'ADMIN_JWT_REFRESH_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
};

export const DEFAULT_PORT = 3000;
