export const CONFIG_VAR = {
  NODE_ENV: "NODE_ENV",
  PORT: "PORT",

  // DATABASE
  DATABASE_URL: "DATABASE_URL",

  // JWT
  JWT_SECRET: "JWT_SECRET",
  JWT_REFRESH_SECRET: "JWT_REFRESH_SECRET",
  ADMIN_JWT_SECRET: "ADMIN_JWT_SECRET",
  ADMIN_JWT_REFRESH_SECRET: "ADMIN_JWT_REFRESH_SECRET",
  JWT_EXPIRES_IN: "JWT_EXPIRES_IN",
  JWT_REFRESH_EXPIRES_IN: "JWT_REFRESH_EXPIRES_IN",
  JWT_FORGOT_SECRET: "JWT_FORGOT_SECRET",
  JWT_FORGOT_EXPIRES_IN: "JWT_FORGOT_EXPIRES_IN",

  //AWS
  AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID",
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY",
  AWS_REGION: "AWS_REGION",
  AWS_BUCKET_S3: "AWS_BUCKET_S3",

  //Mail
  SMTP_HOST: "SMTP_HOST",
  SMTP_PORT: "SMTP_PORT",
  SMTP_EMAIL: "SMTP_EMAIL",
  SMTP_PASS: "SMTP_PASS",

  // Redis
  REDIS_HOST: "REDIS_HOST",
  REDIS_PORT: "REDIS_PORT",
};

export const DEFAULT_PORT = 3000;
